// Datos de ejemplo para la tabla de ventas
export const ventasData = [
    {
        id: "VEN-001",
        cliente: "Juan Pérez",
        fecha: "10/04/2024",
        total: "$1,250.00",
        estado: "Completada",
        metodo: "Tarjeta de Crédito",
    },
    {
        id: "VEN-002",
        cliente: "María López",
        fecha: "15/04/2024",
        total: "$2,340.00",
        estado: "Completada",
        metodo: "Transferencia",
    },
    {
        id: "VEN-003",
        cliente: "Carlos Rodríguez",
        fecha: "20/04/2024",
        total: "$3,450.00",
        estado: "Pendiente",
        metodo: "Efectivo",
    },
    {
        id: "VEN-004",
        cliente: "Ana Martínez",
        fecha: "25/04/2024",
        total: "$1,870.00",
        estado: "Completada",
        metodo: "Tarjeta de Débito",
    },
    {
        id: "VEN-005",
        cliente: "Pedro Sánchez",
        fecha: "30/04/2024",
        total: "$2,560.00",
        estado: "Cancelada",
        metodo: "Tarjeta de Crédito",
    },
    {
        id: "VEN-006",
        cliente: "Laura García",
        fecha: "05/05/2024",
        total: "$3,210.00",
        estado: "Completada",
        metodo: "Transferencia",
    },
    {
        id: "VEN-007",
        cliente: "Miguel Fernández",
        fecha: "10/05/2024",
        total: "$1,980.00",
        estado: "Pendiente",
        metodo: "Efectivo",
    },
    {
        id: "VEN-008",
        cliente: "Sofía Gómez",
        fecha: "15/05/2024",
        total: "$2,740.00",
        estado: "Completada",
        metodo: "Tarjeta de Crédito",
    },
]